# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Shared
  
    # InteractionType - Type of interaction.
    class InteractionType < T::Enum
      enums do
        CLI_EXEC = new('CLI_EXEC')
        TARGET_GENERATE = new('TARGET_GENERATE')
      end
    end

  end
end
