# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Shared
  
    # A PreflightToken is a token that allows access to the OCI distribution endpoints.
    class PreflightToken < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig


      field :auth_token, T.nilable(::String), { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('auth_token') } }


      sig { params(auth_token: T.nilable(::String)).void }
      def initialize(auth_token: nil)
        @auth_token = auth_token
      end
    end
  end
end
