# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Shared
  
    # A set of keys and associated values, attached to a particular version of an Api.
    class VersionMetadataInput < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The key for this metadata.
      field :meta_key, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('meta_key') } }
      # One of the values for this metadata.
      field :meta_value, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('meta_value') } }


      sig { params(meta_key: ::String, meta_value: ::String).void }
      def initialize(meta_key: nil, meta_value: nil)
        @meta_key = meta_key
        @meta_value = meta_value
      end
    end
  end
end
