# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Shared
  
    # A speakeasy workspace
    class Workspace < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :id, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('id') } }

      field :name, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('name') } }

      field :organization_id, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('organization_id') } }

      field :slug, ::String, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('slug') } }

      field :telemetry_disabled, T::Boolean, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('telemetry_disabled') } }

      field :updated_at, ::DateTime, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :verified, T::Boolean, { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('verified') } }

      field :oci_repo, T.nilable(::String), { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('oci_repo') } }

      field :oci_repo_created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('oci_repo_created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }


      sig { params(created_at: ::DateTime, id: ::String, name: ::String, organization_id: ::String, slug: ::String, telemetry_disabled: T::Boolean, updated_at: ::DateTime, verified: T::Boolean, oci_repo: T.nilable(::String), oci_repo_created_at: T.nilable(::DateTime)).void }
      def initialize(created_at: nil, id: nil, name: nil, organization_id: nil, slug: nil, telemetry_disabled: nil, updated_at: nil, verified: nil, oci_repo: nil, oci_repo_created_at: nil)
        @created_at = created_at
        @id = id
        @name = name
        @organization_id = organization_id
        @slug = slug
        @telemetry_disabled = telemetry_disabled
        @updated_at = updated_at
        @verified = verified
        @oci_repo = oci_repo
        @oci_repo_created_at = oci_repo_created_at
      end
    end
  end
end
