# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module SpeakeasyClientSDK
  module Shared
    # Key-Value pairs associated with a request
    class RequestMetadata < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig


      field :key, T.nilable(String), { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('key') } }

      field :value, T.nilable(String), { 'format_json': { 'letter_case': ::SpeakeasyClientSDK::Utils.field_name('value') } }


      sig { params(key: T.nilable(String), value: T.nilable(String)).void }
      def initialize(key: nil, value: nil)
        @key = key
        @value = value
      end
    end
  end
end
