# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/versionmetadatainput'
require_relative '../shared/error'
require_relative '../shared/versionmetadata'

module OpenApiSDK
  module Operations

    class InsertVersionMetadataRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The ID of the Api to insert metadata for.
      field :api_id, String, { 'path_param': { 'field_name': 'apiID', 'style': 'simple', 'explode': false } }
      # The version ID of the Api to insert metadata for.
      field :version_id, String, { 'path_param': { 'field_name': 'versionID', 'style': 'simple', 'explode': false } }
      # A JSON representation of the metadata to insert.
      field :version_metadata_input, Shared::VersionMetadataInput, { 'request': { 'media_type': 'application/json' } }


      sig { params(api_id: String, version_id: String, version_metadata_input: Shared::VersionMetadataInput).void }
      def initialize(api_id: nil, version_id: nil, version_metadata_input: nil)
        @api_id = api_id
        @version_id = version_id
        @version_metadata_input = version_metadata_input
      end
    end


    class InsertVersionMetadataResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :content_type, String

      field :status_code, Integer
      # Default error response
      field :error, T.nilable(Shared::Error)

      field :raw_response, T.nilable(Faraday::Response)
      # OK
      field :version_metadata, T.nilable(Shared::VersionMetadata)


      sig { params(content_type: String, status_code: Integer, error: T.nilable(Shared::Error), raw_response: T.nilable(Faraday::Response), version_metadata: T.nilable(Shared::VersionMetadata)).void }
      def initialize(content_type: nil, status_code: nil, error: nil, raw_response: nil, version_metadata: nil)
        @content_type = content_type
        @status_code = status_code
        @error = error
        @raw_response = raw_response
        @version_metadata = version_metadata
      end
    end
  end
end
