# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module SpeakeasyClientSDK
  autoload :SDK, 'speakeasy_client_sdk/sdk'
  autoload :Shared, 'speakeasy_client_sdk/models/shared'
  autoload :Operations, 'speakeasy_client_sdk/models/operations'
  autoload :Apis, 'speakeasy_client_sdk/apis'
  autoload :ApiEndpoints, 'speakeasy_client_sdk/apiendpoints'
  autoload :Metadata, 'speakeasy_client_sdk/metadata'
  autoload :Schemas, 'speakeasy_client_sdk/schemas'
  autoload :Artifacts, 'speakeasy_client_sdk/artifacts'
  autoload :Auth, 'speakeasy_client_sdk/auth'
  autoload :Requests, 'speakeasy_client_sdk/requests'
  autoload :Github, 'speakeasy_client_sdk/github'
  autoload :Organizations, 'speakeasy_client_sdk/organizations'
  autoload :Reports, 'speakeasy_client_sdk/reports'
  autoload :ShortURLs, 'speakeasy_client_sdk/shorturls'
  autoload :Suggest, 'speakeasy_client_sdk/suggest'
  autoload :Embeds, 'speakeasy_client_sdk/embeds'
  autoload :Events, 'speakeasy_client_sdk/events'
end

require_relative 'speakeasy_client_sdk/utils/t'
require_relative 'speakeasy_client_sdk/utils/utils'
require_relative 'speakeasy_client_sdk/utils/metadata_fields'
require_relative 'speakeasy_client_sdk/sdkconfiguration'
