# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require_relative 'speakeasy_client_sdk/utils/utils'
require_relative 'speakeasy_client_sdk/utils/metadata_fields'
module SpeakeasyClientSDK
  autoload :SDK, 'speakeasy_client_sdk/sdk'
  autoload :SDKConfiguration, 'speakeasy_client_sdk/sdkconfiguration'
  autoload :Shared, 'speakeasy_client_sdk/models/shared'
  autoload :Operations, 'speakeasy_client_sdk/models/operations'
  autoload :Apis, 'speakeasy_client_sdk/apis'
  autoload :ApiEndpoints, 'speakeasy_client_sdk/apiendpoints'
  autoload :Metadata, 'speakeasy_client_sdk/metadata'
  autoload :Schemas, 'speakeasy_client_sdk/schemas'
  autoload :Requests, 'speakeasy_client_sdk/requests'
  autoload :Plugins, 'speakeasy_client_sdk/plugins'
  autoload :Embeds, 'speakeasy_client_sdk/embeds'
end
