workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    -OAS:
        inputs:
            - location: https://speakeasy.com/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/-oas
targets:
    speakeasy-client-sdk:
        target: ruby
        source: -OAS
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/-oas-ruby-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
