# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class GetAccessTokenRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The workspace ID
      field :workspace_id, ::String, { 'query_param': { 'field_name': 'workspace_id', 'style': 'form', 'explode': true } }


      sig { params(workspace_id: ::String).void }
      def initialize(workspace_id: nil)
        @workspace_id = workspace_id
      end
    end
  end
end
