# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class GetOASSummaryRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig


      field :namespace_name, ::String, { 'path_param': { 'field_name': 'namespace_name', 'style': 'simple', 'explode': false } }

      field :revision_reference, ::String, { 'path_param': { 'field_name': 'revision_reference', 'style': 'simple', 'explode': false } }


      sig { params(namespace_name: ::String, revision_reference: ::String).void }
      def initialize(namespace_name: nil, revision_reference: nil)
        @namespace_name = namespace_name
        @revision_reference = revision_reference
      end
    end
  end
end
