# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class GetWorkspaceAccessRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # Unique identifier of the generation target.
      field :gen_lock_id, T.nilable(::String), { 'query_param': { 'field_name': 'genLockId', 'style': 'form', 'explode': true } }


      sig { params(gen_lock_id: T.nilable(::String)).void }
      def initialize(gen_lock_id: nil)
        @gen_lock_id = gen_lock_id
      end
    end
  end
end
