# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class PostWorkspaceEventsRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig


      field :request_body, T::Array[::SpeakeasyClientSDK::Shared::CliEvent], { 'request': { 'media_type': 'application/json' } }
      # Unique identifier of the workspace.
      field :workspace_id, T.nilable(::String), { 'path_param': { 'field_name': 'workspaceID', 'style': 'simple', 'explode': false } }


      sig { params(request_body: T::Array[::SpeakeasyClientSDK::Shared::CliEvent], workspace_id: T.nilable(::String)).void }
      def initialize(request_body: nil, workspace_id: nil)
        @request_body = request_body
        @workspace_id = workspace_id
      end
    end
  end
end
