# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class RevokeEmbedAccessTokenRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The ID of the EmbedToken to revoke.
      field :token_id, ::String, { 'path_param': { 'field_name': 'tokenID', 'style': 'simple', 'explode': false } }


      sig { params(token_id: ::String).void }
      def initialize(token_id: nil)
        @token_id = token_id
      end
    end
  end
end
