# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class RunPluginRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The ID of the plugin to run.
      field :plugin_id, ::String, { 'path_param': { 'field_name': 'pluginID', 'style': 'simple', 'explode': false } }
      # The filter to apply to the query.
      field :filters, T.nilable(::SpeakeasyClientSDK::Shared::Filters), { 'query_param': { 'field_name': 'filters', 'serialization': 'json' } }


      sig { params(plugin_id: ::String, filters: T.nilable(::SpeakeasyClientSDK::Shared::Filters)).void }
      def initialize(plugin_id: nil, filters: nil)
        @plugin_id = plugin_id
        @filters = filters
      end
    end
  end
end
