# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class Style < T::Enum
      enums do
        STANDARDIZE = new('standardize')
        RESOURCE = new('resource')
      end
    end

  end
end
