# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class SuggestRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The OAS summary and diagnostics to use for the suggestion.
      field :suggest_request_body, ::SpeakeasyClientSDK::Shared::SuggestRequestBody, { 'request': { 'media_type': 'application/json' } }

      field :x_session_id, ::String, { 'header': { 'field_name': 'x-session-id', 'style': 'simple', 'explode': false } }


      sig { params(suggest_request_body: ::SpeakeasyClientSDK::Shared::SuggestRequestBody, x_session_id: ::String).void }
      def initialize(suggest_request_body: nil, x_session_id: nil)
        @suggest_request_body = suggest_request_body
        @x_session_id = x_session_id
      end
    end
  end
end
