# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module SpeakeasyClientSDK
  module Operations
  

    class SuggestOpenAPIRequest < ::SpeakeasyClientSDK::Utils::FieldAugmented
      extend T::Sig

      # The schema file to upload provided as a multipart/form-data file segment.
      field :request_body, ::SpeakeasyClientSDK::Operations::SuggestOpenAPIRequestBody, { 'request': { 'media_type': 'multipart/form-data' } }

      field :x_session_id, ::String, { 'header': { 'field_name': 'x-session-id', 'style': 'simple', 'explode': false } }


      sig { params(request_body: ::SpeakeasyClientSDK::Operations::SuggestOpenAPIRequestBody, x_session_id: ::String).void }
      def initialize(request_body: nil, x_session_id: nil)
        @request_body = request_body
        @x_session_id = x_session_id
      end
    end
  end
end
