# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'sorbet-runtime'

module OpenApiSDK
  extend T::Sig
  class Events
    extend T::Sig
    # REST APIs for capturing event data

    sig { params(sdk_config: SDKConfiguration).void }
    def initialize(sdk_config)
      @sdk_configuration = sdk_config
    end


    sig { params(request: T.nilable(::OpenApiSDK::Operations::SearchWorkspaceEventsRequest)).returns(::OpenApiSDK::Operations::SearchWorkspaceEventsResponse) }
    def search(request)
      # search - Search events for a particular workspace by any field
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::SearchWorkspaceEventsRequest,
        base_url,
        '/v1/workspace/{workspace_id}/events',
        request,
        @sdk_configuration.globals
      )
      headers = {}
      query_params = Utils.get_query_params(::OpenApiSDK::Operations::SearchWorkspaceEventsRequest, request, @sdk_configuration.globals)
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        req.params = query_params
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::SearchWorkspaceEventsResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, T::Array[::OpenApiSDK::Shared::CliEvent])
          res.cli_event_batch = out
        end
      elsif r.status >= 500 && r.status < 600
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::Error)
          res.error = out
        end
      end
      res
    end


    sig { params(workspace_id: ::String, request_body: T::Array[::OpenApiSDK::Shared::CliEvent]).returns(::OpenApiSDK::Operations::PostWorkspaceEventsResponse) }
    def post(workspace_id, request_body)
      # post - Post events for a specific workspace
      # Sends an array of events to be stored for a particular workspace.
      request = ::OpenApiSDK::Operations::PostWorkspaceEventsRequest.new(
        
        workspace_id: workspace_id,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::PostWorkspaceEventsRequest,
        base_url,
        '/v1/workspace/{workspace_id}/events',
        request,
        @sdk_configuration.globals
      )
      headers = {}
      req_content_type, data, form = Utils.serialize_request_body(request, :request_body, :json)
      headers['content-type'] = req_content_type
      raise StandardError, 'request body is required' if data.nil? && form.nil?
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.post(url) do |req|
        req.headers = headers
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
        if form
          req.body = Utils.encode_form(form)
        elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
          req.body = URI.encode_www_form(data)
        else
          req.body = data
        end
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::PostWorkspaceEventsResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status >= 200 && r.status < 300
      elsif r.status >= 500 && r.status < 600
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::Error)
          res.error = out
        end
      end
      res
    end


    sig { params(workspace_id: ::String, target_id: ::String, after_created_at: T.nilable(::DateTime)).returns(::OpenApiSDK::Operations::GetWorkspaceEventsByTargetResponse) }
    def get_by_target(workspace_id, target_id, after_created_at = nil)
      # get_by_target - Load recent events for a particular workspace
      request = ::OpenApiSDK::Operations::GetWorkspaceEventsByTargetRequest.new(
        
        workspace_id: workspace_id,
        target_id: target_id,
        after_created_at: after_created_at
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::GetWorkspaceEventsByTargetRequest,
        base_url,
        '/v1/workspace/{workspace_id}/events/targets/{target_id}/events',
        request,
        @sdk_configuration.globals
      )
      headers = {}
      query_params = Utils.get_query_params(::OpenApiSDK::Operations::GetWorkspaceEventsByTargetRequest, request, @sdk_configuration.globals)
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        req.params = query_params
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::GetWorkspaceEventsByTargetResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, T::Array[::OpenApiSDK::Shared::CliEvent])
          res.cli_event_batch = out
        end
      elsif r.status >= 500 && r.status < 600
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::Error)
          res.error = out
        end
      end
      res
    end


    sig { params(after_last_event_created_at: T.nilable(::DateTime)).returns(::OpenApiSDK::Operations::GetWorkspaceTargetsResponse) }
    def get_targets(after_last_event_created_at = nil)
      # get_targets - Load targets for a particular workspace
      request = ::OpenApiSDK::Operations::GetWorkspaceTargetsRequest.new(
        
        after_last_event_created_at: after_last_event_created_at
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = "#{base_url}/v1/workspace/events/targets"
      headers = {}
      query_params = Utils.get_query_params(::OpenApiSDK::Operations::GetWorkspaceTargetsRequest, request, @sdk_configuration.globals)
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        req.params = query_params
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::GetWorkspaceTargetsResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, T::Array[::OpenApiSDK::Shared::TargetSDK])
          res.target_sdk_list = out
        end
      elsif r.status >= 500 && r.status < 600
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::Error)
          res.error = out
        end
      end
      res
    end


    sig { params(workspace_id: ::String, after_last_event_created_at: T.nilable(::DateTime)).returns(::OpenApiSDK::Operations::GetWorkspaceTargetsDeprecatedResponse) }
    def get_targets_deprecated(workspace_id, after_last_event_created_at = nil)
      # get_targets_deprecated - Load targets for a particular workspace
      request = ::OpenApiSDK::Operations::GetWorkspaceTargetsDeprecatedRequest.new(
        
        workspace_id: workspace_id,
        after_last_event_created_at: after_last_event_created_at
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        ::OpenApiSDK::Operations::GetWorkspaceTargetsDeprecatedRequest,
        base_url,
        '/v1/workspace/{workspace_id}/events/targets',
        request,
        @sdk_configuration.globals
      )
      headers = {}
      query_params = Utils.get_query_params(::OpenApiSDK::Operations::GetWorkspaceTargetsDeprecatedRequest, request, @sdk_configuration.globals)
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        req.params = query_params
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::GetWorkspaceTargetsDeprecatedResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, T::Array[::OpenApiSDK::Shared::TargetSDK])
          res.target_sdk_list = out
        end
      elsif r.status >= 500 && r.status < 600
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Shared::Error)
          res.error = out
        end
      end
      res
    end
  end
end
