# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'faraday/retry'
require 'sorbet-runtime'
require_relative 'sdk_hooks/hooks'
require_relative 'utils/retries'

module OpenApiSDK
  extend T::Sig

  class SpeakeasyClientSDK
    extend T::Sig

    attr_accessor :auth, :code_samples, :github, :organizations, :publishing_tokens, :workspaces, :events, :reports, :suggest, :schema_store, :short_ur_ls, :artifacts, :subscriptions

    sig do
      params(
        client: T.nilable(Faraday::Connection),
        retry_config: T.nilable(::OpenApiSDK::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        security: T.nilable(Models::Shared::Security),
        security_source: T.nilable(T.proc.returns(Models::Shared::Security)),
        workspace_id: T.nilable(::String),
        server: T.nilable(Symbol),
        server_url: T.nilable(String),
        url_params: T.nilable(T::Hash[Symbol, String])
      ).void
    end
    def initialize(client: nil, retry_config: nil, timeout_ms: nil, security: nil, security_source: nil, workspace_id: nil, server: nil, server_url: nil, url_params: nil)
      ## Instantiates the SDK configuring it with the provided parameters.
      # @param [T.nilable(Faraday::Connection)] client The faraday HTTP client to use for all operations
      # @param [T.nilable(::OpenApiSDK::Utils::RetryConfig)] retry_config The retry configuration to use for all operations
      # @param [T.nilable(Integer)] timeout_ms Request timeout in milliseconds for all operations
      # @param [T.nilable(Models::Shared::Security)] security: The security details required for authentication
      # @param [T.proc.returns(T.nilable(Models::Shared::Security))] security_source: A function that returns security details required for authentication
      # @param [T.nilable(::String)] workspace_id: Configures the workspace_id parameter for all supported operations
      # @param [T.nilable(::Symbol)] server The server identifier to use for all operations
      # @param [T.nilable(::String)] server_url The server URL to use for all operations
      # @param [T.nilable(::Hash<::Symbol, ::String>)] url_params Parameters to optionally template the server URL with

      connection_options = {
        request: {
          params_encoder: Faraday::FlatParamsEncoder
        }
      }
      connection_options[:request][:timeout] = (timeout_ms.to_f / 1000) unless timeout_ms.nil?

      client ||= Faraday.new(**connection_options) do |f|
        f.request :multipart, {}
        # f.response :logger, nil, { headers: true, bodies: true, errors: true }
      end

      if !server_url.nil?
        if !url_params.nil?
          server_url = Utils.template_url(server_url, url_params)
        end
      end

      raise StandardError, "Invalid server \"#{server}\"" if !server.nil? && !SERVERS.key?(server)

      globals = {
        'parameters': {
          'queryParam': {
          },
          'pathParam': {
            'workspace_id': workspace_id,
          },
          'header': {
          }
        }
      }
      hooks = SDKHooks::Hooks.new
      @sdk_configuration = SDKConfiguration.new(
        client,
        hooks,
        retry_config,
        timeout_ms,
        security,
        security_source,
        server_url,
        server,
        globals
      )

      original_server_url = @sdk_configuration.get_server_details.first
      new_server_url, @sdk_configuration.client = hooks.sdk_init(base_url: original_server_url, client: client)
      @sdk_configuration.server_url = new_server_url if new_server_url != original_server_url

      init_sdks
    end

    sig { void }
    def init_sdks
      @auth = Auth.new(@sdk_configuration)
      @code_samples = CodeSamples.new(@sdk_configuration)
      @github = Github.new(@sdk_configuration)
      @organizations = Organizations.new(@sdk_configuration)
      @publishing_tokens = PublishingTokens.new(@sdk_configuration)
      @workspaces = Workspaces.new(@sdk_configuration)
      @events = Events.new(@sdk_configuration)
      @reports = Reports.new(@sdk_configuration)
      @suggest = Suggest.new(@sdk_configuration)
      @schema_store = SchemaStore.new(@sdk_configuration)
      @short_ur_ls = ShortURLs.new(@sdk_configuration)
      @artifacts = Artifacts.new(@sdk_configuration)
      @subscriptions = Subscriptions.new(@sdk_configuration)
    end
  end
end
