# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # An AccessToken is a token that can be used to authenticate with the Speakeasy API.
      class AccessToken
        extend T::Sig
        include Crystalline::MetadataFields


        field :access_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('access_token') } }

        field :claims, Models::Shared::Claims, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('claims') } }

        field :user, Models::Shared::AccessTokenUser, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user') } }

        field :feature_flags, T.nilable(T::Array[Models::Shared::FeatureFlag]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_flags') } }

        field :workspaces, T.nilable(T::Array[Models::Shared::Workspaces]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspaces') } }


        sig { params(access_token: ::String, claims: Models::Shared::Claims, user: Models::Shared::AccessTokenUser, feature_flags: T.nilable(T::Array[Models::Shared::FeatureFlag]), workspaces: T.nilable(T::Array[Models::Shared::Workspaces])).void }
        def initialize(access_token: nil, claims: nil, user: nil, feature_flags: nil, workspaces: nil)
          @access_token = access_token
          @claims = claims
          @user = user
          @feature_flags = feature_flags
          @workspaces = workspaces
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @access_token == other.access_token
          return false unless @claims == other.claims
          return false unless @user == other.user
          return false unless @feature_flags == other.feature_flags
          return false unless @workspaces == other.workspaces
          true
        end
      end
    end
  end
end
