# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class ApiKeyDetails < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :account_type_v2, ::OpenApiSDK::Shared::AccountType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('account_type_v2'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Shared::AccountType, false) } }

      field :enabled_features, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('enabled_features') } }

      field :org_slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('org_slug') } }

      field :telemetry_disabled, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('telemetry_disabled') } }
      # Workspace creation timestamp.
      field :workspace_created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :workspace_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_id') } }

      field :workspace_slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_slug') } }
      # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
      field :feature_flags, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_flags') } }

      field :generation_access_unlimited, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('generation_access_unlimited') } }


      sig { params(account_type_v2: ::OpenApiSDK::Shared::AccountType, enabled_features: T::Array[::String], org_slug: ::String, telemetry_disabled: T::Boolean, workspace_created_at: ::DateTime, workspace_id: ::String, workspace_slug: ::String, feature_flags: T.nilable(T::Array[::String]), generation_access_unlimited: T.nilable(T::Boolean)).void }
      def initialize(account_type_v2: nil, enabled_features: nil, org_slug: nil, telemetry_disabled: nil, workspace_created_at: nil, workspace_id: nil, workspace_slug: nil, feature_flags: nil, generation_access_unlimited: nil)
        @account_type_v2 = account_type_v2
        @enabled_features = enabled_features
        @org_slug = org_slug
        @telemetry_disabled = telemetry_disabled
        @workspace_created_at = workspace_created_at
        @workspace_id = workspace_id
        @workspace_slug = workspace_slug
        @feature_flags = feature_flags
        @generation_access_unlimited = generation_access_unlimited
      end
    end
  end
end
