# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class ApiKeyDetails
        extend T::Sig
        include Crystalline::MetadataFields


        field :workspace_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_id'), required: true } }

        field :workspace_slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_slug'), required: true } }

        field :org_slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('org_slug'), required: true } }

        field :account_type_v2, Models::Shared::AccountType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('account_type_v2'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::AccountType, false) } }

        field :enabled_features, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('enabled_features'), required: true } }

        field :billing_add_ons, Crystalline::Array.new(Models::Shared::BillingAddOn), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_add_ons'), required: true } }

        field :telemetry_disabled, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('telemetry_disabled'), required: true } }
        # Workspace creation timestamp.
        field :workspace_created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_created_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        field :generation_access_unlimited, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('generation_access_unlimited') } }
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :feature_flags, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_flags') } }

        sig { params(workspace_id: ::String, workspace_slug: ::String, org_slug: ::String, account_type_v2: Models::Shared::AccountType, enabled_features: T::Array[::String], billing_add_ons: T::Array[Models::Shared::BillingAddOn], telemetry_disabled: T::Boolean, workspace_created_at: ::DateTime, generation_access_unlimited: T.nilable(T::Boolean), feature_flags: T.nilable(T::Array[::String])).void }
        def initialize(workspace_id:, workspace_slug:, org_slug:, account_type_v2:, enabled_features:, billing_add_ons:, telemetry_disabled:, workspace_created_at:, generation_access_unlimited: nil, feature_flags: nil)
          @workspace_id = workspace_id
          @workspace_slug = workspace_slug
          @org_slug = org_slug
          @account_type_v2 = account_type_v2
          @enabled_features = enabled_features
          @billing_add_ons = billing_add_ons
          @telemetry_disabled = telemetry_disabled
          @workspace_created_at = workspace_created_at
          @generation_access_unlimited = generation_access_unlimited
          @feature_flags = feature_flags
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @workspace_id == other.workspace_id
          return false unless @workspace_slug == other.workspace_slug
          return false unless @org_slug == other.org_slug
          return false unless @account_type_v2 == other.account_type_v2
          return false unless @enabled_features == other.enabled_features
          return false unless @billing_add_ons == other.billing_add_ons
          return false unless @telemetry_disabled == other.telemetry_disabled
          return false unless @workspace_created_at == other.workspace_created_at
          return false unless @generation_access_unlimited == other.generation_access_unlimited
          return false unless @feature_flags == other.feature_flags
          true
        end
      end
    end
  end
end
