# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BillingAddOn < T::Enum


        enums do
          WEBHOOKS = new('webhooks')
          SDK_TESTING = new('sdk_testing')
          CUSTOM_CODE_REGIONS = new('custom_code_regions')
          SNIPPET_AI = new('snippet_ai')
        end
      end
    end
  end
end
