# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # An EmbedAccessTokenResponse contains a token that can be used to embed a Speakeasy dashboard.
    class EmbedAccessTokenResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :access_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('access_token') } }


      sig { params(access_token: ::String).void }
      def initialize(access_token: nil)
        @access_token = access_token
      end
    end
  end
end
