# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Format < T::Enum
        enums do
          JSON = new('json')
          YAML = new('yaml')
        end
      end
    end
  end
end
