# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class GetRevisionsResponse
        extend T::Sig
        include Crystalline::MetadataFields


        field :items, Crystalline::Array.new(Models::Shared::Revision), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('items'), required: true } }

        field :next_page_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('next_page_token'), required: true } }

        sig { params(items: T::Array[Models::Shared::Revision], next_page_token: ::String).void }
        def initialize(items:, next_page_token:)
          @items = items
          @next_page_token = next_page_token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @items == other.items
          return false unless @next_page_token == other.next_page_token
          true
        end
      end
    end
  end
end
