# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # The state of a particular SDK targets github setup
      class GithubSetupStateResponse
        extend T::Sig
        include Crystalline::MetadataFields


        field :app_installed, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('app_installed'), required: true } }

        field :actions, Models::Shared::Actions, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('actions'), required: true } }

        field :secrets, Models::Shared::Secrets, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('secrets'), required: true } }

        sig { params(app_installed: T::Boolean, actions: Models::Shared::Actions, secrets: Models::Shared::Secrets).void }
        def initialize(app_installed:, actions:, secrets:)
          @app_installed = app_installed
          @actions = actions
          @secrets = secrets
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @app_installed == other.app_installed
          return false unless @actions == other.actions
          return false unless @secrets == other.secrets
          true
        end
      end
    end
  end
end
