# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OASSummary
        extend T::Sig
        include Crystalline::MetadataFields


        field :info, Models::Shared::OASInfo, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('info') } }

        field :operations, T::Array[Models::Shared::OASOperation], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('operations') } }


        sig { params(info: Models::Shared::OASInfo, operations: T::Array[Models::Shared::OASOperation]).void }
        def initialize(info: nil, operations: nil)
          @info = info
          @operations = operations
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @info == other.info
          return false unless @operations == other.operations
          true
        end
      end
    end
  end
end
