# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Relationship < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }

      field :workspace_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workspace_id') } }


      sig { params(user_id: ::String, workspace_id: ::String).void }
      def initialize(user_id: nil, workspace_id: nil)
        @user_id = user_id
        @workspace_id = workspace_id
      end
    end
  end
end
