# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # Remote source configuration
    class RemoteSource < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :inputs, T::Array[::OpenApiSDK::Shared::RemoteDocument], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('inputs') } }
      # A document hosted in the registry
      field :output, ::OpenApiSDK::Shared::RemoteDocument, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('output') } }

      field :overlays, T.nilable(T::Array[::OpenApiSDK::Shared::RemoteDocument]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('overlays') } }


      sig { params(inputs: T::Array[::OpenApiSDK::Shared::RemoteDocument], output: ::OpenApiSDK::Shared::RemoteDocument, overlays: T.nilable(T::Array[::OpenApiSDK::Shared::RemoteDocument])).void }
      def initialize(inputs: nil, output: nil, overlays: nil)
        @inputs = inputs
        @output = output
        @overlays = overlays
      end
    end
  end
end
