# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A document hosted in the registry
      class RemoteDocument
        extend T::Sig
        include Crystalline::MetadataFields


        field :registry_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('registry_url') } }


        sig { params(registry_url: ::String).void }
        def initialize(registry_url: nil)
          @registry_url = registry_url
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @registry_url == other.registry_url
          true
        end
      end
    end
  end
end
