# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Revision
        extend T::Sig
        include Crystalline::MetadataFields

        # Format {namespace_id}/{revision_digest}
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :digest, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('digest'), required: true } }

        field :namespace_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('namespace_name'), required: true } }

        field :tags, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tags'), required: true } }

        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        field :updated_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        field :contents_metadata, Crystalline::Nilable.new(Models::Shared::RevisionContentsMetadata), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('contents_metadata') } }

        sig { params(id: ::String, digest: ::String, namespace_name: ::String, tags: T::Array[::String], created_at: ::DateTime, updated_at: ::DateTime, contents_metadata: T.nilable(Models::Shared::RevisionContentsMetadata)).void }
        def initialize(id:, digest:, namespace_name:, tags:, created_at:, updated_at:, contents_metadata: nil)
          @id = id
          @digest = digest
          @namespace_name = namespace_name
          @tags = tags
          @created_at = created_at
          @updated_at = updated_at
          @contents_metadata = contents_metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @digest == other.digest
          return false unless @namespace_name == other.namespace_name
          return false unless @tags == other.tags
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @contents_metadata == other.contents_metadata
          true
        end
      end
    end
  end
end
