# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Secrets
        extend T::Sig
        include Crystalline::MetadataFields


        field :api_key_configured, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('api_key_configured') } }

        field :publishing_secrets_configured, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('publishing_secrets_configured') } }


        sig { params(api_key_configured: T::Boolean, publishing_secrets_configured: T::Boolean).void }
        def initialize(api_key_configured: nil, publishing_secrets_configured: nil)
          @api_key_configured = api_key_configured
          @publishing_secrets_configured = publishing_secrets_configured
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @api_key_configured == other.api_key_configured
          return false unless @publishing_secrets_configured == other.publishing_secrets_configured
          true
        end
      end
    end
  end
end
