# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class SubscriptionType < T::Enum
      enums do
        CLI = new('cli')
      end
    end
  end
end
