# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class SuggestRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :diagnostics, T::Array[::OpenApiSDK::Shared::Diagnostic], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('diagnostics') } }

      field :oas_summary, ::OpenApiSDK::Shared::OASSummary, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('oas_summary') } }

      field :suggestion_type, ::OpenApiSDK::Shared::SuggestRequestBodySuggestionType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('suggestion_type'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Shared::SuggestRequestBodySuggestionType, false) } }


      sig { params(diagnostics: T::Array[::OpenApiSDK::Shared::Diagnostic], oas_summary: ::OpenApiSDK::Shared::OASSummary, suggestion_type: ::OpenApiSDK::Shared::SuggestRequestBodySuggestionType).void }
      def initialize(diagnostics: nil, oas_summary: nil, suggestion_type: nil)
        @diagnostics = diagnostics
        @oas_summary = oas_summary
        @suggestion_type = suggestion_type
      end
    end
  end
end
