# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class SuggestItemsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The prompt to use for the suggestion. Think of this as the "preamble".
        field :prompt, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('prompt'), required: true } }
        # The list of "things" to get suggestions for. One suggestion will be returned for each item in the list.
        field :items, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('items'), required: true } }

        sig { params(prompt: ::String, items: T::Array[::String]).void }
        def initialize(prompt:, items:)
          @prompt = prompt
          @items = items
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @prompt == other.prompt
          return false unless @items == other.items
          true
        end
      end
    end
  end
end
