# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class TargetResource < T::Enum
        enums do
          DOCUMENT = new('document')
        end
      end
    end
  end
end
