# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class UsageSnippets
        extend T::Sig
        include Crystalline::MetadataFields


        field :snippets, Crystalline::Array.new(Models::Shared::UsageSnippet), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('snippets'), required: true } }

        sig { params(snippets: T::Array[Models::Shared::UsageSnippet]).void }
        def initialize(snippets:)
          @snippets = snippets
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @snippets == other.snippets
          true
        end
      end
    end
  end
end
