# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # A document referenced by a workflow
    class WorkflowDocument < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :location, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('location') } }

      field :auth, T.nilable(::OpenApiSDK::Shared::Auth), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('auth') } }


      sig { params(location: ::String, auth: T.nilable(::OpenApiSDK::Shared::Auth)).void }
      def initialize(location: nil, auth: nil)
        @location = location
        @auth = auth
      end
    end
  end
end
