# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A request to add workspace feature flags
      class WorkspaceFeatureFlagRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :feature_flags, T::Array[Models::Shared::WorkspaceFeatureFlag], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_flags') } }


        sig { params(feature_flags: T::Array[Models::Shared::WorkspaceFeatureFlag]).void }
        def initialize(feature_flags: nil)
          @feature_flags = feature_flags
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @feature_flags == other.feature_flags
          true
        end
      end
    end
  end
end
