# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A document referenced by a workflow
      class WorkflowDocument
        extend T::Sig
        include Crystalline::MetadataFields


        field :location, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('location'), required: true } }

        field :auth, Crystalline::Nilable.new(Models::Shared::Auth), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('auth') } }

        sig { params(location: ::String, auth: T.nilable(Models::Shared::Auth)).void }
        def initialize(location:, auth: nil)
          @location = location
          @auth = auth
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @location == other.location
          return false unless @auth == other.auth
          true
        end
      end
    end
  end
end
