# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # A speakeasy workspace
    class Workspace < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

      field :slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('slug') } }

      field :updated_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :verified, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('verified') } }

      field :inactive, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('inactive') } }
      # Deprecated. Use organization.telemetry_disabled instead.
      # 
      # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
      field :telemetry_disabled, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('telemetry_disabled') } }


      sig { params(created_at: ::DateTime, id: ::String, name: ::String, organization_id: ::String, slug: ::String, updated_at: ::DateTime, verified: T::Boolean, inactive: T.nilable(T::Boolean), telemetry_disabled: T.nilable(T::Boolean)).void }
      def initialize(created_at: nil, id: nil, name: nil, organization_id: nil, slug: nil, updated_at: nil, verified: nil, inactive: nil, telemetry_disabled: nil)
        @created_at = created_at
        @id = id
        @name = name
        @organization_id = organization_id
        @slug = slug
        @updated_at = updated_at
        @verified = verified
        @inactive = inactive
        @telemetry_disabled = telemetry_disabled
      end
    end
  end
end
