# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class CreateWorkspaceTokenRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # Unique identifier of the workspace.
      field :workspace_id, ::String, { 'path_param': { 'field_name': 'workspace_id', 'style': 'simple', 'explode': false } }

      field :workspace_token, ::OpenApiSDK::Shared::WorkspaceToken, { 'request': { 'media_type': 'application/json' } }


      sig { params(workspace_id: ::String, workspace_token: ::OpenApiSDK::Shared::WorkspaceToken).void }
      def initialize(workspace_id: nil, workspace_token: nil)
        @workspace_id = workspace_id
        @workspace_token = workspace_token
      end
    end
  end
end
