# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # The publishing token to create
      class CreatePublishingTokenRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :target_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('target_id') } }

        field :target_resource, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('target_resource') } }

        field :token_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('token_name') } }

        field :valid_until, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('valid_until'), 'decoder': Utils.datetime_from_iso_format(false) } }


        sig { params(target_id: ::String, target_resource: ::String, token_name: ::String, valid_until: ::DateTime).void }
        def initialize(target_id: nil, target_resource: nil, token_name: nil, valid_until: nil)
          @target_id = target_id
          @target_resource = target_resource
          @token_name = token_name
          @valid_until = valid_until
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @target_id == other.target_id
          return false unless @target_resource == other.target_resource
          return false unless @token_name == other.token_name
          return false unless @valid_until == other.valid_until
          true
        end
      end
    end
  end
end
