# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CreateSchemaStoreItemRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The OpenAPI specification to store.
        field :spec, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('spec'), required: true } }
        # The package name to use in code snippets / quickstart.
        field :package_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('packageName'), required: true } }
        # The classname of the SDK to use in code snippets / quickstart.
        field :sdk_classname, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sdkClassname'), required: true } }
        # The format of the OpenAPI specification.
        field :format, Models::Operations::Format, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('format'), required: true, 'decoder': Utils.enum_from_string(Models::Operations::Format, false) } }

        sig { params(spec: ::String, package_name: ::String, sdk_classname: ::String, format: Models::Operations::Format).void }
        def initialize(spec:, package_name:, sdk_classname:, format:)
          @spec = spec
          @package_name = package_name
          @sdk_classname = sdk_classname
          @format = format
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @spec == other.spec
          return false unless @package_name == other.package_name
          return false unless @sdk_classname == other.sdk_classname
          return false unless @format == other.format
          true
        end
      end
    end
  end
end
