# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetAccessTokenRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The workspace ID
        field :workspace_id, ::String, { 'query_param': { 'field_name': 'workspace_id', 'style': 'form', 'explode': true } }


        sig { params(workspace_id: ::String).void }
        def initialize(workspace_id: nil)
          @workspace_id = workspace_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @workspace_id == other.workspace_id
          true
        end
      end
    end
  end
end
