# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetApisRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # Metadata to filter Apis on
      field :metadata, T.nilable(T::Hash[Symbol, T::Array[::String]]), { 'query_param': { 'field_name': 'metadata', 'style': 'deepObject', 'explode': true } }
      # Configuration for filter operations
      field :op, T.nilable(::OpenApiSDK::Operations::Op), { 'query_param': { 'field_name': 'op', 'style': 'deepObject', 'explode': true } }


      sig { params(metadata: T.nilable(T::Hash[Symbol, T::Array[::String]]), op: T.nilable(::OpenApiSDK::Operations::Op)).void }
      def initialize(metadata: nil, op: nil)
        @metadata = metadata
        @op = op
      end
    end
  end
end
