# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetCodeSamplePreviewAsyncRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the job to check the status and retrieve results
        field :job_id, ::String, { 'path_param': { 'field_name': 'jobID', 'style': 'simple', 'explode': false } }


        sig { params(job_id: ::String).void }
        def initialize(job_id: nil)
          @job_id = job_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @job_id == other.job_id
          true
        end
      end
    end
  end
end
