# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetGithubSetupStateRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :org, ::String, { 'query_param': { 'field_name': 'org', 'style': 'form', 'explode': true } }

        field :repo, ::String, { 'query_param': { 'field_name': 'repo', 'style': 'form', 'explode': true } }

        field :generate_gen_lock_id, ::String, { 'query_param': { 'field_name': 'generate_gen_lock_id', 'style': 'form', 'explode': true } }

        sig { params(org: ::String, repo: ::String, generate_gen_lock_id: ::String).void }
        def initialize(org:, repo:, generate_gen_lock_id:)
          @org = org
          @repo = repo
          @generate_gen_lock_id = generate_gen_lock_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @org == other.org
          return false unless @repo == other.repo
          return false unless @generate_gen_lock_id == other.generate_gen_lock_id
          true
        end
      end
    end
  end
end
