# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetManifestRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :namespace_name, ::String, { 'path_param': { 'field_name': 'namespace_name', 'style': 'simple', 'explode': false } }

      field :organization_slug, ::String, { 'path_param': { 'field_name': 'organization_slug', 'style': 'simple', 'explode': false } }
      # Tag or digest
      field :revision_reference, ::String, { 'path_param': { 'field_name': 'revision_reference', 'style': 'simple', 'explode': false } }

      field :workspace_slug, ::String, { 'path_param': { 'field_name': 'workspace_slug', 'style': 'simple', 'explode': false } }


      sig { params(namespace_name: ::String, organization_slug: ::String, revision_reference: ::String, workspace_slug: ::String).void }
      def initialize(namespace_name: nil, organization_slug: nil, revision_reference: nil, workspace_slug: nil)
        @namespace_name = namespace_name
        @organization_slug = organization_slug
        @revision_reference = revision_reference
        @workspace_slug = workspace_slug
      end
    end
  end
end
