# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetPublishingTokenTargetByIDRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Unique identifier of the publishing token.
        field :token_id, ::String, { 'path_param': { 'field_name': 'tokenID', 'style': 'simple', 'explode': false } }


        sig { params(token_id: ::String).void }
        def initialize(token_id: nil)
          @token_id = token_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @token_id == other.token_id
          true
        end
      end
    end
  end
end
