# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetWorkspaceFeatureFlagsResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # Error
      field :error, T.nilable(::OpenApiSDK::Shared::Error)
      # Success
      field :workspace_feature_flag_response, T.nilable(::OpenApiSDK::Shared::WorkspaceFeatureFlagResponse)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, error: T.nilable(::OpenApiSDK::Shared::Error), workspace_feature_flag_response: T.nilable(::OpenApiSDK::Shared::WorkspaceFeatureFlagResponse)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, error: nil, workspace_feature_flag_response: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @error = error
        @workspace_feature_flag_response = workspace_feature_flag_response
      end
    end
  end
end
