# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GrantUserAccessToWorkspaceRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # Email of the user to grant access to.
      field :email, ::String, { 'path_param': { 'field_name': 'email', 'style': 'simple', 'explode': false } }
      # Unique identifier of the workspace.
      field :workspace_id, ::String, { 'path_param': { 'field_name': 'workspace_id', 'style': 'simple', 'explode': false } }


      sig { params(email: ::String, workspace_id: ::String).void }
      def initialize(email: nil, workspace_id: nil)
        @email = email
        @workspace_id = workspace_id
      end
    end
  end
end
