# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class IgnoreSubscriptionNamespaceRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The namespace name
        field :namespace_name, ::String, { 'path_param': { 'field_name': 'namespaceName', 'style': 'simple', 'explode': false } }
        # The existing subscription ID
        field :subscription_id, ::String, { 'path_param': { 'field_name': 'subscriptionID', 'style': 'simple', 'explode': false } }


        sig { params(namespace_name: ::String, subscription_id: ::String).void }
        def initialize(namespace_name: nil, subscription_id: nil)
          @namespace_name = namespace_name
          @subscription_id = subscription_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @namespace_name == other.namespace_name
          return false unless @subscription_id == other.subscription_id
          true
        end
      end
    end
  end
end
