# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class LinkGithubAccessRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :installation_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'installation_id', 'style': 'form', 'explode': true } }

        field :github_org, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'github_org', 'style': 'form', 'explode': true } }

        field :github_oidc_token, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'github_oidc_token', 'style': 'form', 'explode': true } }

        sig { params(installation_id: T.nilable(::String), github_org: T.nilable(::String), github_oidc_token: T.nilable(::String)).void }
        def initialize(installation_id: nil, github_org: nil, github_oidc_token: nil)
          @installation_id = installation_id
          @github_org = github_org
          @github_oidc_token = github_oidc_token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @installation_id == other.installation_id
          return false unless @github_org == other.github_org
          return false unless @github_oidc_token == other.github_oidc_token
          true
        end
      end
    end
  end
end
