# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class Schema
        extend T::Sig
        include Crystalline::MetadataFields


        field :content, ::String, { 'multipart_form': { 'content': true } }

        field :file_name, ::String, { 'multipart_form': { 'field_name': 'fileName' } }


        sig { params(content: ::String, file_name: ::String).void }
        def initialize(content: nil, file_name: nil)
          @content = content
          @file_name = file_name
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content == other.content
          return false unless @file_name == other.file_name
          true
        end
      end
    end
  end
end
