# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # Namespace visibility
      class SetVisibilityRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :public, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('public') } }


        sig { params(public: T::Boolean).void }
        def initialize(public: nil)
          @public = public
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @public == other.public
          true
        end
      end
    end
  end
end
