# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class UpdateWorkspaceSettingsRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The workspace settings to update.
      field :workspace_settings, ::OpenApiSDK::Shared::WorkspaceSettings, { 'request': { 'media_type': 'application/json' } }
      # Unique identifier of the workspace.
      field :workspace_id, T.nilable(::String), { 'path_param': { 'field_name': 'workspace_id', 'style': 'simple', 'explode': false } }


      sig { params(workspace_settings: ::OpenApiSDK::Shared::WorkspaceSettings, workspace_id: T.nilable(::String)).void }
      def initialize(workspace_settings: nil, workspace_id: nil)
        @workspace_settings = workspace_settings
        @workspace_id = workspace_id
      end
    end
  end
end
